// Generated by Wrangler by running `wrangler types`

export {};
declare global {
	const KV: KVNamespace;
	const WARPCAST_BASE_URL: "https://client.warpcast.com";
	const NOUNS_SUBGRAPH_URL: "https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns/prod/gn";
	const WARPCAST_ACCESS_TOKEN: string;
	const WARPCAST_API_KEY: string;
	const ALCHEMY_API_KEY: string;
	const QUEUE: Queue;
}
