// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	WARPCAST_BASE_URL: "https://client.warpcast.com";
	NOUNS_SUBGRAPH_URL: "https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns/prod/gn";
	WARPCAST_ACCESS_TOKEN: string;
	WARPCAST_API_KEY: string;
	ALCHEMY_API_KEY: string;
	QUEUE: Queue;
}
